// INDIVIDUAL PERMISSIONS
pub const ADMIN_READ_PERMISSION: u32 = 1 << 0;    // 0001
pub const ADMIN_WRITE_PERMISSION: u32 = 1 << 1;   // 0010
pub const ADMIN_EXECUTE_PERMISSION: u32 = 1 << 2; // 0100
pub const ADMIN_DELETE_PERMISSION: u32 = 1 << 3;  // 1000

// PERMISSION GROUPS
pub const ADMIN_READ_WRITE: u32 = ADMIN_READ_PERMISSION | ADMIN_WRITE_PERMISSION; // 0011
pub const ADMIN_FULL_ACCESS: u32 = ADMIN_READ_PERMISSION | ADMIN_WRITE_PERMISSION | ADMIN_EXECUTE_PERMISSION | ADMIN_DELETE_PERMISSION; // 1111