// INDIVIDUAL PERMISSIONS
const ADMIN_READ_PERMISSION: u32 = 1 << 0;    // 0001
const ADMIN_WRITE_PERMISSION: u32 = 1 << 1;   // 0010
const ADMIN_EXECUTE_PERMISSION: u32 = 1 << 2; // 0100
const ADMIN_DELETE_PERMISSION: u32 = 1 << 3;  // 1000

// PERMISSION GROUPS
const ADMIN_READ_WRITE: u32 = ADMIN_READ_PERMISSION | ADMIN_WRITE_PERMISSION; // 0011
const ADMIN_FULL_ACCESS: u32 = ADMIN_READ_PERMISSION | ADMIN_WRITE_PERMISSION | ADMIN_EXECUTE_PERMISSION | ADMIN_DELETE_PERMISSION; // 1111