// INDIVIDUAL PERMISSIONS
const EQUIP_READ_PERMISSION: u32 = 1 << 0;    // 0001
const EQUIP_WRITE_PERMISSION: u32 = 1 << 1;   // 0010
const EQUIP_EXECUTE_PERMISSION: u32 = 1 << 2; // 0100
const EQUIP_DELETE_PERMISSION: u32 = 1 << 3;  // 1000

// PERMISSION GROUPS
const EQUIP_READ_WRITE: u32 = EQUIP_READ_PERMISSION | EQUIP_WRITE_PERMISSION; // 0011
const EQUIP_FULL_ACCESS: u32 = EQUIP_READ_PERMISSION | EQUIP_WRITE_PERMISSION | EQUIP_EXECUTE_PERMISSION | EQUIP_DELETE_PERMISSION; // 1111