// INDIVIDUAL PERMISSIONS
const USER_READ_PERMISSION: u32 = 1 << 0;    // 0001
const USER_WRITE_PERMISSION: u32 = 1 << 1;   // 0010
const USER_EXECUTE_PERMISSION: u32 = 1 << 2; // 0100
const USER_DELETE_PERMISSION: u32 = 1 << 3;  // 1000

// PERMISSION GROUPS
const USER_READ_WRITE: u32 = USER_READ_PERMISSION | USER_WRITE_PERMISSION; // 0011
const USER_FULL_ACCESS: u32 = USER_READ_PERMISSION | USER_WRITE_PERMISSION | USER_EXECUTE_PERMISSION | USER_DELETE_PERMISSION; // 1111
