// INDIVIDUAL PERMISSIONS

pub const USER_READ_PERMISSION: u32 = 1 << 0;    // 0001
pub const USER_WRITE_PERMISSION: u32 = 1 << 1;   // 0010
pub const USER_EXECUTE_PERMISSION: u32 = 1 << 2; // 0100
pub const USER_DELETE_PERMISSION: u32 = 1 << 3;  // 1000

// PERMISSION GROUPS
pub const USER_READ_WRITE: u32 = USER_READ_PERMISSION | USER_WRITE_PERMISSION; // 0011
pub const USER_FULL_ACCESS: u32 = USER_READ_PERMISSION | USER_WRITE_PERMISSION | USER_EXECUTE_PERMISSION | USER_DELETE_PERMISSION; // 1111