// INDIVIDUAL PERMISSIONS
pub const EQUIP_READ_PERMISSION: u32 = 1 << 0;    // 0001
pub const EQUIP_WRITE_PERMISSION: u32 = 1 << 1;   // 0010
pub const EQUIP_EXECUTE_PERMISSION: u32 = 1 << 2; // 0100
pub const EQUIP_DELETE_PERMISSION: u32 = 1 << 3;  // 1000

// pub PERMISSION GROUPS
pub const EQUIP_READ_WRITE: u32 = EQUIP_READ_PERMISSION | EQUIP_WRITE_PERMISSION; // 0011
pub const EQUIP_FULL_ACCESS: u32 = EQUIP_READ_PERMISSION | EQUIP_WRITE_PERMISSION | EQUIP_EXECUTE_PERMISSION | EQUIP_DELETE_PERMISSION; // 1111